language: python

python: 2.7

sudo: false
cache:
  directories: [$HOME/.cache/pip]

install: pip install sphinx~=1.3.0 git+https://github.com/fabpot/sphinx-php.git

script: sphinx-build -nW -c _build/ -b html -d _build/doctrees . _build/html

branches:
  except:
    - github-comments
